version: '3'
services:
  api:
    build: .
    container_name: seguros_api
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  db:
    container_name: seguros_mongo_db
    image: mongo:latest
    ports:
      - "27015:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=juancsr
      - MONGO_INITDB_ROOT_PASSWORD=juancsr
